workspace = { members = ["pdml-lib"] }

[package]
name = "pdml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdml-lib = { path = "pdml-lib" }