workspace = { members = ["pdml-lib", "pdml-macros", "soup"] }

[package]
name = "pdml"
version = "0.1.0"
edition = "2021"

[dependencies]
pdml-lib = { path = "pdml-lib" }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
